name: ProjectForager
version: 0.1A
main: me.waiaf.pforager.Main
api-version: 1.17
authors: [ WaIaF ]
description: A remake of the game Forager in Minecraft
commands:
  getitem:
    usage: /getitem
    description: dùng để lấy vật phẩm
    aliases: [item]