name: ProjectForager
version: 0.2A
main: me.waiaf.pforager.Main
api-version: 1.17
authors: [ WaIaF ]
description: A remake of the game Forager in Minecraft
commands:
  getitem:
    usage: /getitem
    description: dùng để lấy vật phẩm
    aliases: [item]
  setcoin:
    usage: /setcoin
    description: đặt số coin của người chơi
  setlevel:
    usage: /setlevel
    description: đặt level của người chơi
  setxp:
    usage: /setxp
    description: đặt xp của người chơi